#!/bin/sh

#= build khadas kernels

CMD(){
    echo "# $@"
    "$@"
}

#KERNEL_FLAVOR=rpi
KERNEL_FLAVOR=lts-edge2
ARCH=aarch64
PHOME=~/packages

export USE_CCACHE=1

KERNEL_PKG="linux-$KERNEL_FLAVOR" \
CBUILDROOT=~/sysroot-$ARCH \
BOOTSTRAP_REPO="http://dl-cdn.alpinelinux.org/alpine/edge/main" \
    CMD time ~/aports/scripts/bootstrap.sh $ARCH
