#!/bin/sh

#= build khadas images

#apk add \
#	abuild apk-tools alpine-conf busybox fakeroot syslinux xorriso cmd:mksquashfs

CMD(){
    echo "# $@"
    "$@"
}

PROFILENAME=khadas_img
ARCH=aarch64
PHOME=~/packages
WDIR=~/apline.images.build

rm -rf $WDIR

CMD sh ~/aports/scripts/mkimage.sh --tag edge \
    --outdir ~/alpine.images \
    --arch $ARCH \
    --repository file:///$PHOME/testing \
    --repository https://dl-cdn.alpinelinux.org/alpine/edge/main \
    --workdir $WDIR \
    --profile $PROFILENAME

#    --repository file:///$PHOME/main \


#    --repository file:///$PHOME/test \
#    --repository file:///$PHOME/main \


exit

<<EOF

# need use edge to

~/aports $ cat /etc/apk/repositories
#http://dl-cdn.alpinelinux.org/alpine/v3.21/main
#http://dl-cdn.alpinelinux.org/alpine/v3.21/community

http://dl-cdn.alpinelinux.org/alpine/edge/main
http://dl-cdn.alpinelinux.org/alpine/edge/community

EOF