#!/bin/sh

#= build khadas kernels

CMD(){
    echo "# $@"
    "$@"
}

PROFILENAME=base
PROFILENAME=rpi
PROFILENAME=khadas
KERNEL_FLAVOR=khadas-edge2
#KERNEL_FLAVOR=rpi
ARCH=aarch64
PHOME=~/packages

export BL31=/home/builder/khadas/edge/bl31.bin
export TEE=/home/builder/khadas/edge/tee.bin

KERNEL_PKG="linux-$KERNEL_FLAVOR" \
CBUILDROOT=~/sysroot-$ARCH \
BOOTSTRAP_REPO="http://dl-cdn.alpinelinux.org/alpine/edge/main" \
    CMD time ~/aports/scripts/bootstrap.sh $ARCH
